// Generated by Hive CE
// Do not modify
// Check in to version control

import 'package:hive_ce/hive_ce.dart';
import 'package:tirana/models/reaction_result.dart';

extension HiveRegistrar on HiveInterface {
  void registerAdapters() {
    registerAdapter(ReactionResultAdapter());
  }
}

extension IsolatedHiveRegistrar on IsolatedHiveInterface {
  void registerAdapters() {
    registerAdapter(ReactionResultAdapter());
  }
}
